### ISSUE TITLE
Inline code has a lot of padding ...

### ISSUE THREAD

**Issue by ryanpcmcquen** [TaylanTatli/inkdrop-bera-light-syntax-theme#1]
Maybe this is the way 'Bera' looks, but it seems that inline code has a bit more padding than it should:

![2020_12_27_1609062645__Inkdrop_lPL9HLkYiA](https://user-images.githubusercontent.com/772937/103168209-12e54e80-47e6-11eb-9002-88d7b4801e73.png)

Here's another theme for reference:

![2020_12_27_1609062617__Inkdrop_oy5dagwTI3](https://user-images.githubusercontent.com/772937/103168214-1973c600-47e6-11eb-96ef-90113f6e99c5.png)

Would you consider reducing the left and right padding on inline code?

**Comment by TaylanTatli** [comment]
Well, i use the same style for my websites also. This is how it looks. If a lot of people don't like this, i can change of course.

**Comment by ryanpcmcquen** [comment]
Here is what Bear looks like for reference:

![B75144F6-99FA-440D-9C01-4D75FFFF20F0](https://user-images.githubusercontent.com/772937/103184806-803cc200-486e-11eb-8197-2d8c3e2a78f7.jpeg)

**Comment by ryanpcmcquen** [comment]
The Bera theme looks to me like there is a literal space character on each side. It is all about personal preference though I suppose ...

**Comment by TaylanTatli** [comment]
Edit/Create [styles.less](https://docs.inkdrop.app/manual/style-tweaks) and add this:  
```
.cm-inline-code {
  padding: 4px 0 !important;
}
```  
Is this ok for you?

**Comment by ryanpcmcquen** [comment]
Yeah, I know you can workaround it. I created this issue in case anyone else felt the same way. I will probably just stick with the Papercolor theme for now.

**Comment by TaylanTatli** [comment]
Hi @ryanpcmcquen. It will look like this now:  
![2021 02 25-15 25 37](https://user-images.githubusercontent.com/754514/109154307-2b8aca00-777f-11eb-9016-5a7ac90b7504.png)
