### ISSUE TITLE
It would be nice to be able to see all the line numbers on unhighlighted texts

### ISSUE THREAD

**Issue by aldrincb** [TaylanTatli/inkdrop-bera-light-syntax-theme#2]
When the editor settings are configured like this:
<img width="609" alt="Screen Shot 2021-02-24 at 10 02 14" src="https://user-images.githubusercontent.com/4471559/109044569-67426880-7687-11eb-8a81-253ffd48ea22.png">

The line number is only visible on the line where the cursor is:
<img width="91" alt="Screen Shot 2021-02-24 at 09 59 00" src="https://user-images.githubusercontent.com/4471559/109044184-f438f200-7686-11eb-9953-d0380725c6e8.png">

**Comment by TaylanTatli** [comment]
Hi. It is now fixed.  
![2021 02 25-15 25 37](https://user-images.githubusercontent.com/754514/109154150-f2eaf080-777e-11eb-8419-ee77b6ae7500.png)

**Comment by aldrincb** [comment]
Wonderful! I updated and verified the fixes. Thank you, the themes look very beautiful

**Comment by TaylanTatli** [comment]
Thanks, glad you like it. :blush:
